name: Convert JSON to Base58

on:
  workflow_dispatch:   # 手动触发
  push:
    paths:
      - "scripts/convert.py"  # 或你想监控的文件

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装 Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. 安装依赖
      - name: Install dependencies
        run: pip install requests base58

      # 4. 运行转换脚本
      - name: Run conversion script
        run: python scripts/convert.py

      # 5. 上传 artifact
      - name: Upload Base58 file
        uses: actions/upload-artifact@v4
        with:
          name: luna-tv-config-base58
          path: luna_tv_config_base58.txt

      # 6. 查看文件确认（可选）
      - name: List files
        run: ls -R
