name: Convert JSON to Base58

on:
  push:
    paths:
      - "luna-tv-config.json"
  workflow_dispatch:   # 手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install base58

      - name: Run conversion script
        run: |
          python scripts/convert.py

      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add luna_tv_config_base58.txt
          git commit -m "Auto convert JSON to Base58"
          git push
